import { ReactNode, useEffect } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import { SettingsContextProvider } from "../../contexts/SettingsContext";
import LoadingIndicator from "../LoadingIndicator";

const Navbar = dynamic(() => import("../Navbar"));

type Props = {
  children: ReactNode;
};

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>MyAnimeList User Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {typeof window !== "undefined" ? (
        <SettingsContextProvider>
          <Navbar />
          <main className="xl:container xl:mx-auto">{children}</main>
        </SettingsContextProvider>
      ) : (
        <LoadingIndicator />
      )}
    </>
  );
}
